sudo: false
language:
  - erlang

matrix:
  include:
  - otp_release: 22.0
  - otp_release: 21.0
  - otp_release: 20.1
  - otp_release: 20.0
  - otp_release: 19.3
  - otp_release: 19.2
    dist: trusty
  - otp_release: 19.1
    dist: trusty
  - otp_release: 19.0
    dist: trusty
  - otp_release: 18.3
    dist: trusty
  - otp_release: 18.2
    dist: trusty
  - otp_release: 18.1
    dist: trusty
  - otp_release: 18.0
    dist: trusty
script:
  - LATEST_OTP_RELEASE=22.0
  - "[[ ${TRAVIS_OTP_RELEASE} != ${LATEST_OTP_RELEASE} ]] || make elvis"
  - make
  - make test
deploy:
  provider: script
  script: ./travis-to-hex
  skip_cleanup: true
  on:
    otp_release: 22.0
    repo: for-GET/jesse
    tags: true
